"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Utils = exports.TileXRenderer = exports.TileRenderer = exports.Stage = exports.Sprite = exports.Rect = exports.Point = exports.DefaultRenderer = exports.Color = exports.Canvas = exports.BitmapRenderer = void 0;
const Canvas_1 = require("./components/Canvas");
Object.defineProperty(exports, "Canvas", { enumerable: true, get: function () { return Canvas_1.Canvas; } });
const Color_1 = require("./components/Color");
exports.Color = Color_1.default;
const Point_1 = require("./components/Point");
exports.Point = Point_1.default;
const Rect_1 = require("./components/Rect");
Object.defineProperty(exports, "Rect", { enumerable: true, get: function () { return Rect_1.Rect; } });
const BitmapRenderer_1 = require("./components/renderers/BitmapRenderer");
Object.defineProperty(exports, "BitmapRenderer", { enumerable: true, get: function () { return BitmapRenderer_1.BitmapRenderer; } });
const DefaultRenderer_1 = require("./components/renderers/DefaultRenderer");
Object.defineProperty(exports, "DefaultRenderer", { enumerable: true, get: function () { return DefaultRenderer_1.DefaultRenderer; } });
const TileRenderer_1 = require("./components/renderers/TileRenderer");
Object.defineProperty(exports, "TileRenderer", { enumerable: true, get: function () { return TileRenderer_1.TileRenderer; } });
const TileXRenderer_1 = require("./components/renderers/TileXRenderer");
Object.defineProperty(exports, "TileXRenderer", { enumerable: true, get: function () { return TileXRenderer_1.TileXRenderer; } });
const Sprite_1 = require("./components/Sprite");
Object.defineProperty(exports, "Sprite", { enumerable: true, get: function () { return Sprite_1.Sprite; } });
const Stage_1 = require("./components/Stage");
exports.Stage = Stage_1.default;
// Export Utils as a namespace
exports.Utils = require("./components/Utils");
