import Camera from './Camera';
import { Canvas } from './Canvas';
import Color from './Color';
import Point from './Point';
import Projection from './Projection';
import { DefaultRenderer } from './renderers/DefaultRenderer';
import { TransformCenter } from './TransformCenter';
import { UIMouse, UIMouseConfig } from './UIMouse';
export interface SpriteConfig extends UIMouseConfig {
    id?: string;
    className?: string;
    position?: Point;
    friction?: Point;
    rotation?: number;
    scale?: number;
    alpha?: number;
    vector?: Point;
    canvas?: Canvas;
    transformCenter?: TransformCenter;
    width?: number;
    height?: number;
    color?: Color;
    physics?: boolean;
    smoothing?: boolean;
    mouseEnabled?: boolean;
    alwaysRender?: boolean;
    onTick?(e: Sprite): void;
    renderer?(sprite: Sprite, context: CanvasRenderingContext2D, canvas: HTMLCanvasElement, camera?: Camera): void;
}
export declare class Sprite {
    UID: string;
    __REMOVE: boolean;
    id: string;
    className: string;
    onstage: boolean;
    children: Sprite[];
    position: Point;
    friction: Point;
    rotation: number;
    scale: number;
    alpha: number;
    vector: Point;
    width: number;
    height: number;
    color: Color;
    physics: boolean;
    smoothing: boolean;
    mouseEnabled: boolean;
    _canvas: Canvas;
    canvas: HTMLCanvasElement;
    context: CanvasRenderingContext2D;
    transformCenter: TransformCenter;
    projection: Projection;
    alwaysRender: boolean;
    data: any;
    renderer: typeof DefaultRenderer;
    onTick?(e: Sprite): void;
    onDown?(e: UIMouse): void;
    onMove?(e: UIMouse): void;
    onDrag?(e: UIMouse): void;
    onUp?(e: UIMouse): void;
    onLeave?(e: UIMouse): void;
    onWheel?(e: UIMouse): void;
    onClick?(e: UIMouse): void;
    constructor(config?: SpriteConfig);
    tick(): void;
    project(camera: Camera): void;
    render(context: CanvasRenderingContext2D, canvas: HTMLCanvasElement, camera: Camera): void;
}
